import { test, expect } from '@playwright/test';
test('practice starts through real UI, training spends resources, workers gather and result rematches', async ({ page }) => {
  test.setTimeout(120000);
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
  await page.goto('/'); await page.getByRole('button', { name: 'Start practice' }).click();
  await expect(page.locator('#lobby')).toBeHidden(); await expect(page.locator('#selection-title')).toHaveText('Town Center');
  await page.getByRole('button', { name: /Train Worker/ }).click();
  await expect(page.locator('#food')).toHaveText('150');
  await expect(page.locator('#queue')).toContainText('Worker');
  await page.keyboard.press('.'); await page.getByRole('button', { name: 'Gather food', exact: true }).click();
  await expect(page.locator('#selection-detail')).toContainText('gather');
  await expect.poll(async () => Number(await page.locator('#food').textContent()), { timeout: 30000 }).toBeGreaterThan(150);
  await page.getByRole('button', { name: /^Build House/ }).click();
  await page.mouse.move(950, 430); await page.mouse.click(950, 430);
  await expect(page.locator('#wood')).toHaveText('275');
  await expect(page.locator('#population')).toHaveText('5 / 15', { timeout: 25000 });
  await page.screenshot({ path: 'test-results/economy.png', fullPage: true });
  await page.getByRole('button', { name: /^Build Barracks/ }).click();
  await page.mouse.move(650, 550); await page.mouse.click(650, 550);
  await expect(page.locator('#wood')).toHaveText('100');
  await expect(page.locator('#selection-detail')).toContainText('idle', { timeout: 30000 });
  await page.mouse.click(650, 510);
  await expect(page.locator('#selection-title')).toHaveText('Barracks');
  await page.getByRole('button', { name: /^Train Swordsman/ }).click();
  await expect(page.locator('#gold')).toHaveText('130');
  await expect(page.locator('#queue')).toContainText('Swordsman');
  await expect(page.locator('#population')).toHaveText('6 / 15', { timeout: 20000 });
  await page.getByRole('button', { name: 'Settings and controls' }).click(); await page.getByRole('button', { name: 'Resign match' }).click();
  await expect(page.locator('#result-title')).toHaveText('Your realm has fallen');
  await page.getByRole('button', { name: 'Rematch →', exact: true }).click();
  await expect(page.locator('#results')).toBeHidden(); await expect(page.locator('#food')).toHaveText('200');
  expect(errors).toEqual([]); await page.screenshot({ path: 'test-results/practice.png', fullPage: true });
});
